### ISSUE TITLE
2-byte aligned check is necessary when inserting breakpoint??

### ISSUE THREAD

**Issue by ytlin101** [cole945/binutils-gdb#3]
We have 2-byte aligend check in nds32_breakpoint_from_pc. This results in some fail cases.
Like gdb.cp/nsalias.exp
break *outer::foo
Bad address 0x88b26bd for inserting breakpoint.
Address must be at least 2-byte aligned.
(gdb) 
FAIL: gdb.cp/nsalias.exp: setting breakpoint at *outer::foo

Should we remove this check at this time??

**Comment by cole945** [comment]
Delete the checking code.

Thanks
