### ISSUE TITLE
gdb/i386-tdep.c has been modified unexpectedly

### ISSUE THREAD

**Issue by ytlin101** [cole945/binutils-gdb#4]
The commit has modified gdb/i386-tdep.c. Is this a mistake??

nds32-record: initial works on process-record 
-  frame_unwind_append_unwinder (gdbarch, &i386_epilogue_frame_unwind); 
-  frame_unwind_append_unwinder (gdbarch, &nds32_epilogue_frame_unwind);

**Comment by cole945** [comment]
That's accident XD.
Thanks
