### ISSUE TITLE
simulator often shows "assertion failed" message when using floating toolchain

### ISSUE THREAD

**Issue by ytlin101** [cole945/binutils-gdb#5]
Simulator often shows "interp.c:236: assertion failed - size <= sizeof (unsigned long)" message when executing program compiled using floating toolchain.

A path to this failed assertion is nds32_decode32_sdc --> __nds32_st --> SIM_ASSERT.
nds32_decode32_sdc will always pass "8" as size to __nds32_st, and the given size break the assertion.

**Comment by cole945** [comment]
Merged your fix.  Thanks
